import type { Challenge } from "./types";

export const challenges: Challenge[] = [
  {
    id: "accessible-name",
    title: "The Silent Button",
    category: "Accessible names",
    difficulty: "Beginner",
    summary: "A compact icon control has no programmatic name.",
    issue: "The control exposes no useful accessible name to assistive technology.",
    why: "A person using a screen reader may hear an unnamed button without knowing what it does.",
    repair: "Give the control a concise accessible name that describes its action.",
    verification: "Activate the repaired control and confirm its accessible name describes the action.",
  },
  {
    id: "form-label",
    title: "The Unnamed Field",
    category: "Forms",
    difficulty: "Beginner",
    summary: "A form field has visible text but no programmatic label.",
    issue: "The visible text is not correctly associated with the input.",
    why: "Assistive technology may announce the field without the context a sighted user receives.",
    repair: "Associate a real label with the input using native HTML semantics.",
    verification: "Focus the field and confirm the label is announced with the control.",
  },
  {
    id: "contrast",
    title: "Faint Text",
    category: "Contrast",
    difficulty: "Beginner",
    summary: "Important text is too close in tone to its background.",
    issue: "The foreground and background do not provide enough contrast.",
    why: "Low contrast can make information difficult to perceive, especially for people with low vision.",
    repair: "Choose a foreground/background combination that meets the applicable contrast requirement.",
    verification: "Recheck the ratio and confirm the intended text size passes.",
  },
  {
    id: "focus-loss",
    title: "Lost Focus",
    category: "Focus",
    difficulty: "Intermediate",
    summary: "Closing a dialog leaves keyboard focus in an unexpected place.",
    issue: "Focus is not returned to a sensible control after the interface changes.",
    why: "Keyboard and assistive-technology users can lose their place and become disoriented.",
    repair: "Return focus to the control that launched the dialog when appropriate.",
    verification: "Open and close the dialog with the keyboard and observe the focus destination.",
  },
  {
    id: "focus-visible",
    title: "Invisible Focus",
    category: "Keyboard",
    difficulty: "Beginner",
    summary: "Keyboard users can move through controls but cannot see where focus is.",
    issue: "The focus indicator is missing or visually indistinguishable.",
    why: "Without visible focus, a keyboard user cannot reliably tell which control will receive input.",
    repair: "Provide a strong, visible focus indicator that is not removed by default styling.",
    verification: "Tab through the interface and identify the focused control at every step.",
  },
  {
    id: "keyboard-action",
    title: "Mouse Only",
    category: "Keyboard",
    difficulty: "Beginner",
    summary: "A custom interaction responds to a pointer but not to the keyboard.",
    issue: "An interactive operation is unavailable through keyboard input.",
    why: "People who cannot or do not use a mouse can be blocked from completing the task.",
    repair: "Use a native interactive element or implement the appropriate keyboard interaction.",
    verification: "Complete the same action without using a pointer.",
  },
  {
    id: "focus-order",
    title: "Wrong Turn",
    category: "Navigation",
    difficulty: "Intermediate",
    summary: "The focus sequence jumps around the page.",
    issue: "Keyboard focus moves in an order that does not preserve the intended meaning.",
    why: "Unexpected focus movement increases effort and can make a workflow difficult to understand.",
    repair: "Use logical document structure and avoid artificial focus ordering.",
    verification: "Tab through the interface and confirm the sequence follows the visual and logical flow.",
  },
  {
    id: "error-message",
    title: "Where Did I Go Wrong?",
    category: "Forms",
    difficulty: "Beginner",
    summary: "A failed form submission gives an unclear error state.",
    issue: "The error is not clearly associated with the affected control or explained to the user.",
    why: "People may know a submission failed but not know what to fix.",
    repair: "Provide clear error text and associate it with the relevant field.",
    verification: "Submit invalid data and confirm the error is understandable and discoverable.",
  },
  {
    id: "semantics",
    title: "Looks Like a Button",
    category: "Semantics",
    difficulty: "Intermediate",
    summary: "A styled element looks interactive but does not have native button semantics.",
    issue: "Visual appearance does not match the element's programmatic meaning.",
    why: "Assistive technology and keyboard behavior depend on correct semantics.",
    repair: "Use a native button when the control performs a button action.",
    verification: "Inspect and operate the repaired control using keyboard and assistive technology expectations.",
  },
  {
    id: "pointer-dependence",
    title: "Hover Is Not Enough",
    category: "Interaction",
    difficulty: "Intermediate",
    summary: "Important information is exposed only through a pointer hover.",
    issue: "The interaction is unavailable to users who cannot reproduce the pointer behavior.",
    why: "Essential information should not depend on one input method.",
    repair: "Provide an equivalent accessible interaction that can be reached without a pointer.",
    verification: "Access the same information using keyboard interaction.",
  },
];

export const learnTopics = [
  ["Perceivable", "Information must be presented in ways people can perceive."],
  ["Operable", "Controls and navigation must be usable through supported input methods."],
  ["Understandable", "Interfaces and feedback should behave predictably and communicate clearly."],
  ["Robust", "Content should work reliably with browsers and assistive technologies."],
  ["Semantic HTML", "Native elements provide meaningful structure and built-in behavior."],
  ["Focus", "Keyboard focus should be visible, logical, and intentionally managed."],
  ["Forms", "Labels, instructions, validation, and errors should be understandable."],
  ["Contrast", "Text and meaningful interface information need sufficient visual distinction."],
] as const;
