import type { Challenge } from "./types";

export const challenges: Challenge[] = [
  {
    id: "accessible-name", title: "The Silent Button", category: "Accessible names", difficulty: "Beginner",
    summary: "A compact icon control has no programmatic name.",
    scenario: "A settings control is represented by an icon. Visually it is obvious, but its programmatic name is missing.",
    impact: "A screen-reader user may encounter a button without enough information to know its purpose.",
    principle: "Robust",
    investigation: "Interact with the control and consider what a non-visual user would be told about its purpose.",
    issue: "The control exposes no useful accessible name to assistive technology.",
    why: "Interactive controls need a meaningful name so their purpose can be communicated to users of assistive technology.",
    repair: "Give the control a concise accessible name through native text or an appropriate accessible-name technique.",
    verification: "Inspect the control's accessible name and activate it. The name should communicate the action without relying on the visual icon.",
    references: ["https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/"],
  },
  {
    id: "form-label", title: "The Unnamed Field", category: "Forms", difficulty: "Beginner",
    summary: "A form field has visible text but no programmatic label.",
    scenario: "A form shows 'Email address' beside an input, but the text is not associated with the control.",
    impact: "Assistive technology may announce the field without the context a sighted user receives visually.",
    principle: "Perceivable",
    investigation: "Focus the field and inspect the relationship between the visible label and the input.",
    issue: "The visible text is not correctly associated with the input.",
    why: "A real label gives a form control an understandable, programmatically associated name.",
    repair: "Associate a real label with the input using native HTML semantics.",
    verification: "Focus the field and confirm that the label is announced with the control.",
    references: ["https://www.w3.org/WAI/tutorials/forms/labels/"],
  },
  {
    id: "contrast", title: "Faint Text", category: "Contrast", difficulty: "Beginner",
    summary: "Important text is too close in tone to its background.",
    scenario: "Supporting text looks subtle, but the foreground/background combination makes it difficult to distinguish.",
    impact: "Low contrast can make information difficult to perceive, particularly for people with low vision.",
    principle: "Perceivable",
    investigation: "Compare the foreground and background colors and calculate their contrast ratio.",
    issue: "The foreground and background do not provide enough contrast for the intended text.",
    why: "Sufficient contrast helps people distinguish text and meaningful interface information from its background.",
    repair: "Choose a foreground/background combination that meets the applicable WCAG contrast requirement.",
    verification: "Recalculate the ratio and confirm the intended text size passes the applicable threshold.",
    references: ["https://www.w3.org/TR/WCAG22/#contrast-minimum"],
  },
  {
    id: "focus-loss", title: "Lost Focus", category: "Focus", difficulty: "Intermediate",
    summary: "Closing a dialog leaves keyboard focus in an unexpected place.",
    scenario: "A user opens a dialog from an edit control, completes the interaction, and closes it.",
    impact: "Keyboard and assistive-technology users can lose their place and become disoriented.",
    principle: "Operable",
    investigation: "Open the interaction with the keyboard, close it, and observe where focus is placed afterward.",
    issue: "Focus is not returned to a sensible control after the interface changes.",
    why: "Focus management is part of the interaction model when content changes or dialogs close.",
    repair: "Return focus to the control that launched the dialog when that control remains available.",
    verification: "Open and close the dialog with the keyboard and confirm focus returns to the launching control.",
    references: ["https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/"],
  },
  {
    id: "focus-visible", title: "Invisible Focus", category: "Keyboard", difficulty: "Beginner",
    summary: "Keyboard users can move through controls but cannot see where focus is.",
    scenario: "The interface responds to Tab, but the focus indicator has been removed or is too weak.",
    impact: "A keyboard user cannot reliably tell which control will receive input.",
    principle: "Operable",
    investigation: "Move through the controls with Tab and identify the active control at each step.",
    issue: "The focus indicator is missing or visually indistinguishable.",
    why: "Visible focus is necessary for users to understand where keyboard interaction is currently positioned.",
    repair: "Provide a strong, visible focus indicator and do not remove it without supplying an equivalent.",
    verification: "Tab through the interface and identify the focused control at every step.",
    references: ["https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html"],
  },
  {
    id: "keyboard-action", title: "Mouse Only", category: "Keyboard", difficulty: "Beginner",
    summary: "A custom interaction responds to a pointer but not to the keyboard.",
    scenario: "A visually interactive control works when clicked but cannot be reached or activated using normal keyboard interaction.",
    impact: "People who cannot or do not use a mouse can be blocked from completing the task.",
    principle: "Operable",
    investigation: "Put the pointer down and try to reach and activate the same operation using the keyboard.",
    issue: "An interactive operation is unavailable through keyboard input.",
    why: "Functionality should be operable through keyboard input where keyboard interaction is supported.",
    repair: "Use a native interactive element or implement the appropriate keyboard interaction and focus behavior.",
    verification: "Complete the same operation without using a pointer.",
    references: ["https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html"],
  },
  {
    id: "focus-order", title: "Wrong Turn", category: "Navigation", difficulty: "Intermediate",
    summary: "The focus sequence jumps around the page.",
    scenario: "The visual layout suggests one reading path, but keyboard focus moves through controls in a confusing order.",
    impact: "Unexpected focus movement increases effort and can make a workflow difficult to understand.",
    principle: "Operable",
    investigation: "Tab through the interface and compare the focus sequence with the intended visual and logical flow.",
    issue: "Keyboard focus moves in an order that does not preserve the intended meaning.",
    why: "A predictable focus order helps people understand and complete multi-step interfaces.",
    repair: "Use logical document structure and avoid artificial positive tabindex values that create an unrelated sequence.",
    verification: "Tab through the interface and confirm the sequence follows the visual and logical flow.",
    references: ["https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html"],
  },
  {
    id: "error-message", title: "Where Did I Go Wrong?", category: "Forms", difficulty: "Beginner",
    summary: "A failed form submission gives an unclear error state.",
    scenario: "A form rejects input, but the message does not clearly explain what failed or which control needs attention.",
    impact: "People may know a submission failed but not know what to fix.",
    principle: "Understandable",
    investigation: "Submit invalid data and look for a message that identifies the affected control and the required correction.",
    issue: "The error is not clearly associated with the affected control or explained to the user.",
    why: "Clear errors reduce uncertainty and help users recover from failed input.",
    repair: "Provide clear error text and associate it with the relevant field using visible and programmatic relationships.",
    verification: "Submit invalid data and confirm the error is understandable, discoverable, and connected to the affected field.",
    references: ["https://www.w3.org/WAI/tutorials/forms/notifications/"],
  },
  {
    id: "semantics", title: "Looks Like a Button", category: "Semantics", difficulty: "Intermediate",
    summary: "A styled element looks interactive but does not have native button semantics.",
    scenario: "A visual design makes a generic element look like a button even though it does not expose button behavior.",
    impact: "Assistive technology and keyboard behavior depend on programmatic semantics, not just appearance.",
    principle: "Robust",
    investigation: "Inspect the element type and try to operate it without relying on pointer-specific styling.",
    issue: "Visual appearance does not match the element's programmatic meaning.",
    why: "Native semantics provide expected keyboard behavior, roles, and interaction patterns.",
    repair: "Use a native button when the control performs a button action.",
    verification: "Inspect and operate the repaired control using keyboard interaction and expected button semantics.",
    references: ["https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Accessibility/HTML"],
  },
  {
    id: "pointer-dependence", title: "Hover Is Not Enough", category: "Interaction", difficulty: "Intermediate",
    summary: "Important information is exposed only through a pointer hover.",
    scenario: "A tooltip or essential explanation appears only while a pointer hovers over a target.",
    impact: "People using keyboard input or other interaction methods may never receive information necessary to understand the interface.",
    principle: "Operable",
    investigation: "Try to reach the same information without a pointer and determine whether the content remains available.",
    issue: "The interaction is unavailable to users who cannot reproduce the pointer behavior.",
    why: "Essential information should not depend on one input method.",
    repair: "Provide an equivalent accessible interaction that can be reached without a pointer and remains discoverable.",
    verification: "Access the same information using keyboard interaction.",
    references: ["https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus.html"],
  },
];

export const learnTopics = [
  { id: "perceivable", title: "Perceivable", text: "Information must be presented in ways people can perceive.", challengeId: "contrast" },
  { id: "operable", title: "Operable", text: "Controls and navigation must be usable through supported input methods.", challengeId: "keyboard-action" },
  { id: "understandable", title: "Understandable", text: "Interfaces and feedback should behave predictably and communicate clearly.", challengeId: "error-message" },
  { id: "robust", title: "Robust", text: "Content should work reliably with browsers and assistive technologies.", challengeId: "semantics" },
  { id: "semantic-html", title: "Semantic HTML", text: "Native elements provide meaningful structure and built-in behavior.", challengeId: "semantics" },
  { id: "accessible-names", title: "Accessible names", text: "Interactive controls need names that communicate their purpose to assistive technology.", challengeId: "accessible-name" },
  { id: "focus", title: "Focus", text: "Keyboard focus should be visible, logical, and intentionally managed.", challengeId: "focus-visible" },
  { id: "forms", title: "Forms and errors", text: "Labels, instructions, validation, and error messages should help people complete tasks.", challengeId: "error-message" },
  { id: "navigation", title: "Navigation", text: "Structure and focus order should help users understand where they are and where they can go next.", challengeId: "focus-order" },
  { id: "interaction", title: "Motion and interaction", text: "Interaction should remain usable without depending on one pointer behavior or unnecessary motion.", challengeId: "pointer-dependence" },
];